language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter